### ISSUE TITLE
Fire stalebot

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-doc-it#480]
## Describe the desired behavior

Either we fix docit bugs more frequently, or stale bot shall be disabled.

## Describe the current behavior

It sometimes closes bugs that are still worth fixing.

**Comment by emclaug2** [comment]
Repo config change.

**Comment by emclaug2** [comment]
There's an option to add feature branch exempt labels here.  @daileytj

**Comment by daileytj** [comment]
https://github.com/marketplace/stale

**Comment by huayunh** [comment]
Fixed by #629
