### ISSUE TITLE
Stop using execCommand

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-doc-it#482]
### Describe the desired behavior

Use [the clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

### Describe the current behavior

document.execCommand is used. It is deprecated. https://github.com/pxblue/doc-it/blob/85e66cb6244941c2332c0d8dc6b00178c6f1c06a/src/app/shared/utilities.tsx#L33

**Comment by emclaug2** [comment]
Use this for Colors, Deeplinking, Icons, etc.  Anywhere you click to copy something.
