### ISSUE TITLE
Drawer content overflows when using a notification banner

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-doc-it#536]
#### Describe the bug
When we display a notification banner, the Eaton Logo at the bottom of the drawer is clipped

#### What is the expected behavior?
The bottom of the drawer content should not be clipped

#### What are the steps to reproduce?
1. Go to doc site when the banner is enabled
2. Observe that the drawer is clipped

#### Screenshots or links to minimum reproduction example
<div>
<img height="500" alt="image" src="https://user-images.githubusercontent.com/29152776/160669368-82f2d6c1-ec72-4e54-9793-eb4247ec2512.png">
vs.
<img height="500" alt="image" src="https://user-images.githubusercontent.com/29152776/160669489-202dea6a-64f7-4bac-bf0e-0df10c86ea25.png">
</div>
		
#### Anything else to add?
This is caused because inside of the DrawerLayout component, the drawer is given position: fixed and height: 100%, which means it has height 100% relative to the full window. 

Rather than making any changes in the component (since this relies on context that exists outside of the component scope), we should just handle this as a style override on the doc site to have the height calculated based on the presence or absence of the additional banner (`calc(100% - 64px)` or `calc(100% - 56px)` depending on screen size).

**Comment by joebochill** [comment]
Keep it open. This could be a good one to tackle in R26 or during the mui5 update.

**Comment by bkarambe** [comment]
@joebochill Looks like this has been fixed here https://github.com/brightlayer-ui/doc-it/commit/e96f0ddb944fb48b2dbf60fed094432f8809389d

**Comment by ektaghag-eaton** [comment]
This is fixed here https://github.com/etn-ccis/blui-doc-it/pull/558
