### ISSUE TITLE
Icon usage instructions need to be updated for MUI 5

### ISSUE THREAD

**Issue by joebochill** [etn-ccis/blui-doc-it#571]
#### Describe the bug
Icon usage instructions for React show the MUI v4 syntax

#### What is the expected behavior?
These should show the new syntax (new package name)

#### What are the steps to reproduce?
1. Go to the iconography page
2. Select a MUI icon
3. Expand the React usage instructions in the sidebar

#### Screenshots or links to minimum reproduction example
<img width="373" alt="image" src="https://user-images.githubusercontent.com/29152776/181497176-2bd669cb-3095-444e-ba62-efe559a74ecb.png">

**Comment by ektaghag-eaton** [comment]
Icon usage instructions updated as per MUI5

<img width="343" alt="Screenshot 2024-07-05 at 3 17 36 PM" src="https://github.com/etn-ccis/blui-doc-it/assets/133877691/8a825c0b-69c1-4541-8ed6-f84e4c3fe865">
