### ISSUE TITLE
Icons fail to download SVG and PNG files from Material UI

### ISSUE THREAD

**Issue by jeffvg** [etn-ccis/blui-doc-it#590]
#### Describe the bug
User reported that the Notifications SVG icon download was an empty 0kb file and that the PNG format threw an error.
Additional information can be found in group email box
#### What is the expected behavior?
Any material icon can be downloaded in any format
#### What are the steps to reproduce?
1. Go to https://brightlayer-ui.github.io/style/icon-library?icon=Notifications&isMaterial=true
2. Click on SVG download (empty file)
3. Click on PNG download (error is displayed)

#### Screenshots / Screen recording
PNG
![image](https://user-images.githubusercontent.com/37150565/199738460-25a4f563-50ec-44ae-86c6-7233bc86d016.png).

SVG (able to download, but file size 0 bytes)
https://user-images.githubusercontent.com/25982779/208843275-8b48eeb3-d549-4245-b054-9c9cbbe3ceb5.mov

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Suggested fix

Currently we are using this in the utilityFunctions.tsx and if the v6 is changed to v8 the PNG works.
<img width="875" alt="image" src="https://user-images.githubusercontent.com/37150565/199740004-5b2d8808-c811-4774-bfbf-ac1bd59556d3.png">

In the api/index.tsx we currently use v6 and changing this to v8 the SVG file download works.
<img width="896" alt="image" src="https://user-images.githubusercontent.com/37150565/199740648-dfa56c4d-bc78-441f-a843-7fb20d17538a.png">

**Comment by bkarambe** [comment]
SVG icon can be downloaded without any error, but PNG is throwing an error.

https://user-images.githubusercontent.com/25982779/208842712-e4f2d38d-b542-4120-8129-bca28356854c.mov

**Comment by daileytj** [comment]
Once this is fixed, do a spot check on a few icons to ensure they are all still working

**Comment by daileytj** [comment]
Dynamically pull in the version number from the metadata file

**Comment by joebochill** [comment]
@daileytj is correct on this one. The only way to fix it is to dynamically pull the version from the metadata file. Otherwise, no matter which version we try to hardcode, some icons will work and some won't.
