### ISSUE TITLE
Update warning about pseudo class first-child

### ISSUE THREAD

**Issue by jeffvg** [etn-ccis/blui-doc-it#615]
#### Describe the bug
the warning about pseudo class first-child that would happen once in a few clicks to happening 14 times in one click. If you scroll to the bottom of "apps using blui" page then nav to roadmap page you should see this 14 times 
#### What is the expected behavior?
no warnings 
#### What are the steps to reproduce?
1. Go to...apps using blui page, scroll to bottom of page
2. Click on...roadmap page with dev tools open

#### Screenshots / Screen recording
![image](https://user-images.githubusercontent.com/37150565/208697987-adbf42ea-3abc-42e9-bdf7-4ff4303902bf.png)

#### Code snippet / Link to minimum reproduction example

updating all the first-child to first-of-type cleans up the warnings but unsure about final results

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/37150565/208698273-862540eb-e100-44be-83bb-5626317a3d29.png">

#### Anything else to add?
https://github.com/emotion-js/emotion/issues/2325

**Comment by huayunh** [comment]
This might have been fixed already in the latest PRs.

**Comment by huayunh** [comment]
- https://github.com/etn-ccis/blui-doc-it/commit/7d9fe48ca091702eb1a9fc60f347943caf5cb9ee
- https://github.com/etn-ccis/blui-doc-it/commit/f40e73c322d47e6cdc8eacc7ff6c6f9fb9d57fb8
