### ISSUE TITLE
can you let github actions bot shut up

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-doc-it#630]
#### Describe the bug / expected behavior

In [this PR](https://github.com/etn-ccis/blui-doc-it/pull/625), the github-actions bot dropped "Thank you for the master pull request" every time there is a new push to the master branch. This should only be done once per PR.

**Comment by JeffGreiner-eaton** [comment]
by default it will place the comment for anyone pushing a commit. Research this to see if this can be triggered once

**Comment by joebochill** [comment]
We have BLUI-3596 which covers this
