### ISSUE TITLE
Update doc-it landing page footer links

### ISSUE THREAD

**Issue by JeffGreiner-eaton** [etn-ccis/blui-doc-it#644]
#### Describe the bug / expected behavior
Links to Component Libraries, Figma Sticker Sheet & Resources not linked out to corresponding resources 
#### What are the steps to reproduce?

1. Go to https://brightlayer-ui.github.io/
2. Scroll to bottom of page and select any of the mentioned links from above

#### Screenshots / Screen recording
![image](https://user-images.githubusercontent.com/119693939/215186733-244168d9-f50e-426d-b10c-3349e327a379.png)

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by joebochill** [comment]
May need to look into whether there is a special syntax for react-router-dom link component for relative vs. absolute links
