### ISSUE TITLE
Unwanted semicolons in the Latest Updates text 

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-doc-it#650]
#### Describe the bug / expected behavior
There are two unwanted semi colons in the Latest Updates text

#### What are the steps to reproduce?

1. yarn start
2. Scroll down to Latest Updates section

#### Screenshots / Screen recording
<img width="1792" alt="Screenshot 2023-02-28 at 6 17 30 PM" src="https://user-images.githubusercontent.com/120575281/221861336-13a4729c-f87d-4467-a39c-8a512f22c985.png">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

**Comment by huayunh** [comment]
I am a fan of using semicolons as long as [they are grammatically correct](https://www.grammarly.com/blog/semicolon/).

**Comment by turjoc120** [comment]
Hi @surajeaton,

 I would like to work on this issue and help resolve it. Could you please assign this issue to me?

**Comment by surajeaton** [comment]
> Hi @surajeaton,
> 
> I would like to work on this issue and help resolve it. Could you please assign this issue to me?

@turjoc120 Here you go.
