### ISSUE TITLE
Dev resource page is listing all CLI templates when a specific framework is selected

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-doc-it#664]
## Describe the bug / expected behavior

The developer resources page is currently showing all CLI templates, no matter which framework is selected.

## What are the steps to reproduce?

1. Go to https://brightlayer-ui-dev.github.io/resources/developer
2. Click on "Angular", "React" or "React Native" on the top navigation tab
3. Look at the "CLI" templates list
4. Notice how every single template is listed

## Screenshots / Screen recording

![image](https://user-images.githubusercontent.com/8997218/229381519-fadaa2cb-79f9-4c97-99cb-c2b64d4190d8.png)

#### Suggested fix

Everything in this clause should be properly tagged using the field `applies` with their appropriate framework, 

https://github.com/etn-ccis/blui-doc-it/blob/2eab3e176911ef0700e8d05a637c0590fc9b1a4c/src/__configuration__/resources/index.tsx#L218-L287

**Comment by surajeaton** [comment]
Already been addressed in #670
