### ISSUE TITLE
Include Mano & Ragha in the current maintainers' list

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-doc-it#666]
## Describe the desired feature/functionality
In the "CURRENT MAINTAINERS" list on the home page, include both @raghavenc5 and @Manoj1907

## Suggested implementation details

Add to https://github.com/etn-ccis/blui-doc-it/blob/dev/src/__configuration__/contributors/currentMaintainers.ts 

Optionally include photos too

**Comment by JeffGreiner-eaton** [comment]
Need some pictures is they want
